#!/usr/bin/env node
/**
 * The IMPORTANT.md status table — derived, never hand-written.
 *
 *   node scripts/task-status.mjs            print the table
 *   node scripts/task-status.mjs --write    regenerate it inside docs/fix-plan.md
 *   node scripts/task-status.mjs --check    fail if the doc is out of date  (CI)
 *
 * A task counts as DONE only when a spec file exists for it under
 * `app/e2e/tasks/task-NN-*.spec.ts` and that file contains at least one real
 * `test(` — not `test.skip` or `test.fixme`. Claiming a fix without a test is
 * therefore impossible: the table reports "not started" until the spec lands, and
 * CI fails if the committed table disagrees with the files on disk.
 */
import { readFileSync, readdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const APP = join(dirname(fileURLToPath(import.meta.url)), "..");
const REPO = join(APP, "..");
const IMPORTANT = join(REPO, "docs/IMPORTANT.md");
const PLAN = join(REPO, "docs/fix-plan.md");
const TASK_DIR = join(APP, "e2e/tasks");

const BEGIN = "<!-- BEGIN TASK STATUS -->";
const END = "<!-- END TASK STATUS -->";

/**
 * The vendored list is an explicit numbered list on purpose. The original file is
 * prose where some lines wrap and some real items start lowercase, so any
 * heuristic parser mis-groups them — it silently merged five items on the first
 * attempt. An explicit `N. text` line is unambiguous.
 */
function readTasks() {
  const body = readFileSync(IMPORTANT, "utf8");
  const tasks = [];
  for (const line of body.split("\n")) {
    const m = /^(\d+)\.\s+(.*\S)\s*$/.exec(line);
    if (m) tasks.push({ n: Number(m[1]), text: m[2] });
  }
  if (!tasks.length) throw new Error(`no numbered items found in ${IMPORTANT}`);
  return tasks;
}

function readSpecs() {
  if (!existsSync(TASK_DIR)) return new Map();
  const byTask = new Map();
  for (const f of readdirSync(TASK_DIR)) {
    const m = /^task-(\d+)-[\w-]+\.spec\.ts$/.exec(f);
    if (!m) continue;
    const src = readFileSync(join(TASK_DIR, f), "utf8");
    const real = (src.match(/^\s*test\(/gm) ?? []).length;
    const skipped = (src.match(/^\s*test\.(skip|fixme)\(/gm) ?? []).length;
    byTask.set(Number(m[1]), { file: f, tests: real, skipped });
  }
  return byTask;
}

/** Short label per item, and which fix-plan.md PR carries it. */
const META = {
  1:  ["Multi-select and move layers", "PR 2"],
  2:  ["Line and arrow render invisible", "PR 3 + PR 4"],
  3:  ["Pencil tool does nothing", "PR 5"],
  4:  ["Layer up/down should move one step", "PR 6"],
  5:  ["Text cannot be resized vertically", "PR 7"],
  6:  ["Stroke/fill ignored on images", "PR 8"],
  7:  ["Stroke ignored on text", "PR 9"],
  8:  ["Usernames on canvas, comments, members", "PR 10"],
  9:  ["Save PNG/SVG/.merodesign in Tauri", "PR 11"],
  10: ["Comments overlay navbar dropdowns", "PR 12"],
  11: ["Images not embedded in code export", "PR 13"],
  12: ["Usernames in project settings", "PR 10"],
  13: ["SVG icon: bundle, logos, favicon, metadata", "PR 15"],
  14: ["Rounded corners on rectangles", "PR 14"],
  15: ["Close the Figma feature gap", "roadmap"],
};

function build() {
  const tasks = readTasks();
  const specs = readSpecs();
  const rows = [];
  let done = 0;
  let tested = 0;

  for (const t of tasks) {
    const spec = specs.get(t.n);
    const isDone = !!spec && spec.tests > 0;
    if (isDone) {
      done++;
      tested += spec.tests;
    }
    const [name, pr] = META[t.n] ?? [t.text.slice(0, 48), "—"];
    rows.push(
      `| ${t.n} | ${name} | ${isDone ? "**done**" : "not started"} | ${pr} | ${
        spec ? `\`${spec.file}\`` : "—"
      } | ${spec ? `${spec.tests} × 2 = ${spec.tests * 2}` : "0"} |`,
    );
  }

  const extra = [...specs.entries()]
    .filter(([n]) => !tasks.some((t) => t.n === n))
    .map(([n, s]) => `${n}: ${s.file}`);

  const table = [
    `_Generated by \`pnpm tasks\` from \`IMPORTANT.md\` and \`app/e2e/tasks/\`. Do not edit by hand —_`,
    `_\`pnpm tasks --check\` fails CI if this drifts. A task is only "done" when a spec file_`,
    `_exists for it and contains at least one live test; the count is × 2 because every spec_`,
    `_runs in both the browser and the Tauri project._`,
    "",
    `**${done} of ${tasks.length} done** · ${tested} task tests × 2 projects = ${tested * 2} runs in CI`,
    "",
    "| # | Item | Status | Plan | Spec | CI runs |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows,
    ...(extra.length ? ["", `Specs not tied to an IMPORTANT.md line: ${extra.join(", ")}`] : []),
  ].join("\n");

  return { table, done, total: tasks.length };
}

const { table, done, total } = build();
const mode = process.argv[2];

if (mode === "--write" || mode === "--check") {
  const doc = readFileSync(PLAN, "utf8");
  if (!doc.includes(BEGIN) || !doc.includes(END)) {
    console.error(`✗ ${PLAN} is missing the ${BEGIN} / ${END} markers`);
    process.exit(1);
  }
  const next =
    doc.slice(0, doc.indexOf(BEGIN) + BEGIN.length) +
    "\n" +
    table +
    "\n" +
    doc.slice(doc.indexOf(END));

  if (mode === "--write") {
    writeFileSync(PLAN, next);
    console.log(`✓ docs/fix-plan.md updated — ${done}/${total} done`);
  } else if (next !== doc) {
    console.error("✗ docs/fix-plan.md status table is out of date. Run: pnpm tasks --write");
    process.exit(1);
  } else {
    console.log(`✓ status table matches the specs on disk — ${done}/${total} done`);
  }
} else {
  console.log(table);
}
